lib/resolve.js
package.json
test/unit/resolve.js

I am trying to use ied with a private registry that is only available over `https`. This PR allows ied to detect and switch between http or https as needed depending on the url
Also I reworked `package.json` to support `npm run lint`

Adds https support and reworks linter/test scripts

---

lib/resolve.js

[Here](https://github.com/alexanderGugel/ied/blob/d3b066f83cff4cd416b142f1b63bb019f43524c6/lib/install_cmd.js#L65) you throw the error is something went wrong. But actually error is being caught and process will keep going and fail later.
I encountered with it when tried to run install command on `package.json` with links on GitHub. I expected to get a proper error message, but just got:
```
TypeError: Cannot read property 'dist' of null
at expose (/Users/just-boris/coding/ied/lib/expose.js:48:31)
at /Users/just-boris/coding/ied/node_modules/async/lib/async.js:356:13
```
With this fix, it will be ok
```
Error: No satisfying target found for redux-router@github:just-boris/redux-router
at /Users/just-boris/coding/ied/lib/resolve.js:84:17
at resolvePending …
```

Do not catch errors during callback dispatching

---

lib/init_cmd.js

User-friendly error output when exiting from the initialization process

---

lib/init_cmd.js

Ooops, sorry, but in the current version the error output always.This PR fixes this.

Fix error output when exiting from the initialization process

---

lib/cache.js

Skip root folder for cached tarballs as well as in fetch

---

lib/config.js

#62 — this makes ied work with non-POSIX shells like [fish-shell](http://fishshell.com/).

Support non-POSIX shells (#62)

---

.gitignore
README.md
package.json
test/mocha.opts
test/setup.js

Tests are very slow because they simulate `ied install`:
```
install
✓ should install browserify@12.0.1 (19685ms)
✓ should install tape@4.2.2 (8569ms)
✓ should install express@4.13.3 (16876ms)
✓ should install mocha@2.3.4 (4246ms)
✓ should install lodash@3.10.1 (4019ms)
✓ should install gulp@https://github.com/gulpjs/gulp/archive/4.0.tar.gz (25571ms)
✓ should install grunt@0.3.1 (13590ms)
```
This speeds it up _considerably_ by caching HTTP requests:
```
install
✓ should install browserify@12.0.1 (3344ms)
✓ should install tape@4.2.2 (420ms)
✓ should install express@4.13.3 (613ms)
✓ should install mocha@2.3.4 (379ms)
✓ should install lodash@3.10.1 (457ms)
✓ should install gulp@https://github.com/gulpjs/gulp/archive/4.0.tar.gz (7444ms)
✓ should install grunt@0.3.1 (1280ms)
```
This does it …

Cache HTTP requests in tests

---

lib/resolvers/npm-registry.js
test/unit/resolve.js

The fix is very small, but can bring a big performance profit.
Consider the following dependency tree:
```
packageA
├── packageB
│   └── packageC (^1.0.0)
└── packageC (1.1.1)
```
Now package uid generated by specified version from package.json. That means that you get different packages as `packageC@^1.0.0` and `packageC@1.1.1` even if it will be resolved to the same version `1.1.1`
After this fix, the resolved version will be used and `packageC` instances will be merged and we will make fewer requests.

Use resolved package version as uid

---

lib/resolve.js
lib/resolvers/npm-registry.js
test/unit/resolve.js

now `ied install babel-core@latest` is supported
closes #74

resolve dependency version as tag

---

README.md

The URL should specify the branch name, otherwise the image shows the status of the latest build which happened to run on Travis, which can be from any other branch.
---
That's why it currently shows as failing - because it's picking up your rebirth branch.

Fix travis badge in README to show status of master branch

---

.travis.yml
lib/index.js
lib/install.js
lib/run.js
lib/run_cmd.js
package.json
test/integration/install.js
test/unit/install.js

closes #82
Also, this feature was asked in #43 as the necessary thing to install `electron-prebuilt`.
It is not ready to merge, yet, I'd like just share my results, and I want to add more tests before this will be merged.
And there is a thing with native packages. They require `node-gyp` to be installed. NPM carries bundled `node-gyp` command. To get this work with IED, we need to install it: `npm install -g node-gyp`. Maybe it should be mentioned in the docs.

Invoke postinstallation hooks

---

lib/config.js
lib/expose.js
lib/install.js
lib/link.js

The default folder symlink requires elevated permissions to work on
Windows. By using junctions we can remove this requirement and work
functionally the same way.
This should resolve the issue in #35

Use junction as symlink type on Windows

---

USAGE.txt
src/cmd.js

Adds npm-like aliases for `start`, `build` and `stop`. I also added these sub-commands to `USAGE.txt` (and the already existing `test` sub-command), but there's not much to say about them, so what's your take on including them?

Add `start`, `build` and `stop` as `ied run` aliases

---

package.json
src/cmd.js
src/install.js
src/install_cmd.js

- Adds a progress bar for HTTP downloads similar to what `master` has
- Adds a `-v, --verbose` option to show `Install package@version`
(disables progress bar)
- Adds a `-d, --debug` option to show (in addition to the above) the
current `resolve` output
Currently we pass the specified log level to the functions that need it, which isn't "scalable" when more logging is added, so we might want to consider something better suited. Would you rather we look at that right away or rather delay until necessary?
What do you think about the way to specify log level through such command line arguments? To me it's a very appealing approach, because it provides a nice and descriptive way to provide a certain log level. If we end up with something like this, we could document the options along with how …

Add progress bar for downloads and log levels

---

src/registry.js

Reapply functionality in https://github.com/alexanderGugel/ied/blob/fde1311d495bb935fd926189d13523c3c5fd35a4/lib/resolvers/npm-registry.js#L50
Based on some testing and a browse through the linking code in `rebirth`, it should handle scoped modules just fine with this addition (and the folder structure in my tests is looking good).

Support scoped modules

---

src/cmd.js
src/install.js
src/install_cmd.js

Shows progress similarly to how webpack does, and shows it for the whole installation process instead of individual dependencies. Looks like this:
Doesn't look like it affects permformance very radically. I'm looking at a difference between 
```
ied i  1.44s user 0.37s system 80% cpu 2.253 total
```
and 
```
ied i  1.11s user 0.27s system 57% cpu 2.393 total
```
In short, it's implemented so that for every module we resolve we increment the total amount we need to install. For every resolved local module or fetched module we increment the count for modules that are ready. This is abstracted by `.total` and `.tick()` in the `progress` package. It also provides the formatting we use to display progress.

Replace per module download progress with progress reporting over the whole process

---

src/install.js

This was left in after moving progress reporting to the whole installation process

Remove unused progress reference

---

Makefile
package.json
src/cmd.js

Babel Compilation
Added inline sourcemaps to the lib built files to get proper stack traces:
from:
```
/Users/olivier/Developer/nodejs/ied/ied/lib/registry.js:97
_assert2.default.equal(statusCode, 200, 'error status code ' + uri + ': ' + error);
^
AssertionError: error status code https://registry.npmjs.org/eslint/node_modules/eslint: undefined
at checkStatus (/Users/olivier/Developer/nodejs/ied/ied/lib/registry.js:97:20)
at SafeSubscriber._next (/Users/olivier/Developer/nodejs/ied/ied/lib/registry.js:134:12)
at SafeSubscriber.__tryOrSetError (/Users/olivier/Developer/nodejs/ied/ied/node_modules/rxjs/src/Subscriber.ts:247:10)
at SafeSubscriber.next (/Users/olivier/Developer/nodejs/ied/ied/node_modules/rxjs/src/Subscriber.ts:191:23)
at Subscriber._next …
```

Add inline source maps to compiled lib

---

src/git.js
src/install.js

`install`
Added support for git endpoints. However did not found a public git remote with a known ssh host key to test against. GitHub/Bitbucket/GitLab git-like url are automatically resolved as tarballs currently (via npm-package-arg).
Does allow private ssh git clone given that you have a working `SSH_AUTH_SOCK` in your environment (eg. passwordless ssh).

Add support for git public/private remotes

---

USAGE.txt
src/cmd.js
src/install.js
src/install_cmd.js

Adds a --production flag (similar to npm). If `--production=true`, `devDependencies` will be ignored during the installation.

Add --production flag

---

guides/proxy.md

As requested via email:
>I was wondering if ied solves the problem of using npm through a proxy? The problem is discussed in many threads, basically npm very aggressively opens simultaneous connections when downloading Node modules, and this is a problem for some proxies, especially corporate proxies, which start to refuse connections.
>It seems that npm has no way of allowing connectivity to be restricted, say to 10 simultaneous connections - can you tell me if ied offers better configurability in this regard?

Add proxy guide

---

package.json

none
Fix #164 
Needle package has released a new version (1.1.0) with automatically encode URI which result in a 404 for any call to NPM registry with a version range.
Example: babel-plugin-transform-es2015-parameters >=6.9.0 <7.0.0
`https://registry.npmjs.org/babel-plugin-transform-es2015-parameters/%3E=6.9.0%20%3C7.0.0`
If you try this URL in a browser or with CURL it will works and give you a valid response with a 200 status code but not with `needle`.

Fix broken install for package using caret version

---

src/git.js

Fixes:
```
TypeError: Path must be a string. Received undefined
at assertPath (path.js:8:11)
at Object.posix.join (path.js:479:5)
at Object.extract [as fetch] (/usr/local/lib/node_modules/ied/lib/git.js:93:29)
at MergeMapSubscriber.fetchWithRetry [as project] (/usr/local/lib/node_modules/ied/lib/install.js:633:28)
at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/ied/node_modules/rxjs/operator/mergeMap.js:110:27)
at MergeMapSubscriber._next (/usr/local/lib/node_modules/ied/node_modules/rxjs/operator/mergeMap.js:100:18)
at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:89:18)
at DistinctSubscriber._next (/usr/local/lib/node_modules/ied/node_modules/rxjs/operator/distinct.js:75:26)
at DistinctSubscriber.Subscriber.next …
```

config.storageDir is no longer present
